import time
import random
import os

# Simulate 4 AIs with dummy responses (replace with real API calls later)
AI_MODELS = ["Grok-3", "Claude-3.5", "GPT-4o", "Gemini-1.5"]

def simulate_ai_logic(idea, model):
    time.sleep(0.5)  # Simulate thinking time (fast mode)
    # Dummy React code generation based on idea
    colors = ['cyan', 'emerald', 'purple', 'rose', 'amber']
    color = random.choice(colors)
    
    return f"""// Generated by {model} for idea: {idea}
import React from 'react';
import GridLayout from 'react-grid-layout'; // For draggable square

export default function Square_{random.randint(1,1000)}() {{
  const [data, setData] = React.useState(0); // Live data placeholder

  React.useEffect(() => {{
    const interval = setInterval(() => {{
      setData(Math.random() * 100); // Simulate live swarm data
    }}, 5000);
    return () => clearInterval(interval);
  }}, []);

  return (
    <div className="neon-square bg-black border-2 border-{color}-400 p-4 rounded-lg shadow-[0_0_20px_{color}] draggable h-full w-full flex flex-col justify-between">
      <div>
          <h2 className="text-{color}-400 font-bold mb-2 uppercase tracking-widest text-xs">{idea} // {model}</h2>
          <div className="h-px w-full bg-gradient-to-r from-{color}-500/50 to-transparent mb-4"></div>
      </div>
      
      <p className="text-white font-mono text-2xl font-bold">${{data.toFixed(2)}}</p>
      
      {{/* Add logic here, e.g., red alert if data < 50 */}}
      {{ data < 50 && <div className="text-red-400 animate-pulse text-xs font-bold mt-2">[ALERT: THRESHOLD BREACH]</div> }}
      
      <div className="text-[10px] text-zinc-600 mt-2 font-mono">{random.randint(1000,9999)} OPS/SEC</div>
    </div>
  );
}}"""

def generate_variations(base_code, idea, num_variations=10):
    base_dir = "squares"
    os.makedirs(base_dir, exist_ok=True)
    
    generated_files = []
    
    print(f"\n[EMPIRE ENGINE] Spinning up {num_variations} variations...")
    
    for i in range(1, num_variations + 1):
        # Vary design: colors, glows, layouts, animations
        variation_code = base_code
        
        # Randomize colors heavily for variations
        palettes = ['cyan', 'emerald', 'purple', 'rose', 'amber', 'blue', 'orange', 'lime']
        color = random.choice(palettes)
        shadow_intensity = random.choice([10, 20, 30, 50])
        border_width = random.choice([1, 2, 4])
        
        variation_code = variation_code.replace("border-cyan-400", f"border-{color}-500") 
        variation_code = variation_code.replace("text-cyan-400", f"text-{color}-400") 
        variation_code = variation_code.replace("shadow-[0_0_20px_cyan]", f"shadow-[0_0_{shadow_intensity}px_{color}]")
        variation_code = variation_code.replace("border-2", f"border-{border_width}")
        
        filename = f"square_variation_{i}.tsx"
        filepath = os.path.join(base_dir, filename)
        with open(filepath, 'w') as f:
            f.write(variation_code)
        
        generated_files.append(filepath)
        # Visual loading bar
        print(f"[{'=' * i}{' ' * (num_variations - i)}] {int((i/num_variations)*100)}% \r", end="")
        
    print("\n")
    return generated_files

def main():
    print("Welcome to Empire Engine v0.1")
    idea = input("Type your idea for a new square: ")
    
    if not idea: idea = "Live PnL Tracker"
    
    logics = []
    for model in AI_MODELS:
        print(f"> Querying {model}...")
        logic = simulate_ai_logic(idea, model)
        logics.append(logic)

    # Pick the first as base (or combine in real version)
    base_logic = logics[0]

    # Generate 10 design variations (100 is a lot for a demo, sticking to 10 for speed)
    files = generate_variations(base_logic, idea, num_variations=10)
    
    print(f"\nDone! Generated {len(files)} design options in 'squares/'.")
    print(f"Sample content of {files[0]}:\n")
    with open(files[0], 'r') as f:
        print(f.read())

if __name__ == "__main__":
    main()
